name: "Agent Bug"
description: "Bug report with repro suitable for autonomous fixing"
title: "[bug]: "
labels: ["agent", "bug"]
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What is happening?
    validations:
      required: true

  - type: textarea
    id: repro
    attributes:
      label: Reproduction steps
      description: Exact steps/commands and inputs to reproduce.
      placeholder: |
        1) ...
        2) ...
        3) ...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual behavior / logs
    validations:
      required: false

  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance criteria (checklist)
      value: |
        - [ ] Bug no longer reproduces
        - [ ] Test added to prevent regression
    validations:
      required: true

  - type: textarea
    id: verification
    attributes:
      label: Verification commands (must pass)
      value: |
        uv sync --dev --frozen
        uv run ruff check .
        uv run mypy .
        uv run pytest
    validations:
      required: true
